In [3]:
import numpy as np

Creating arrays

In [5]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [7]:
a = [1, 2, 3, 4, 5, "hello"]
a

[1, 2, 3, 4, 5, 'hello']

In [ ]:
np.array(a)
#in arrays all elements must be of the same data type.  If we try to create an array with mixed data types, NumPy will upcast the elements to a common data type that can accommodate all the values. In this case, since "hello" is a string, all the other elements will be converted to strings as well.

array(['1', '2', '3', '4', '5', 'hello'], dtype='<U21')

In [ ]:
b = [1,2,3.5]
b
#In this case, since 3.5 is a float, all the other elements will be converted to floats as well.

[1, 2, 3.5]

In [10]:
np.array(b)

array([1. , 2. , 3.5])

In [ ]:
d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
d
#lists can be nested to create multi-dimensional arrays. In this case, we have a 2D list with three rows and three columns. but lists are vectors

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(d)
# arrays can also be multi-dimensional. In this case, we have a 2D array with three rows and three columns. Unlike lists, arrays are homogeneous, meaning that all elements must be of the same data type.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [15]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [17]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [18]:
 np.arange(0, 1, 0.2)


array([0. , 0.2, 0.4, 0.6, 0.8])

In [ ]:
np.arange(5,0,-1)
# arange() function is used to create an array with a range of values. It takes three arguments: start, stop, and step. The start argument specifies the starting value of the range, the stop argument specifies the ending value of the range (exclusive), and the step argument specifies the increment between each value in the range. If the step argument is negative, the range will be created in reverse order.

array([5, 4, 3, 2, 1])

In [21]:
np.linspace(0, 0.4, 5)

array([0. , 0.1, 0.2, 0.3, 0.4])

In [23]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.zeros(5)
arr
#zeros() function is used to create an array filled with zeros. It takes a single argument, which specifies the shape of the array. In this case, we are creating a 1D array with 5 elements, all initialized to zero.

array([0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros((5,3))
arr
#zeros() function can also be used to create multi-dimensional arrays. In this case, we are creating a 2D array with 5 rows and 3 columns, all initialized to zero.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones(5)
arr
#ones() function is used to create an array filled with ones. It takes a single argument, which specifies the shape of the array. In this case, we are creating a 1D array with 5 elements, all initialized to one.

array([1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones((5,3))
arr
#ones() function can also be used to create multi-dimensional arrays. In this case, we are creating a 2D array with 5 rows and 3 columns, all initialized to one.

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr = np.linspace(0,6,5, endpoint=False, dtype=int)
arr
#The `linspace()` function is used to create an array of evenly spaced values over a specified range. It takes several arguments, including the start and stop values, the number of samples to generate, and optional parameters such as `endpoint` and `dtype`. In this case, we are creating an array of 5 evenly spaced integers between 0 and 6 (exclusive), with the `endpoint` parameter set to `False`, which means that the stop value (6) will not be included in the output array. The `dtype` parameter is set to `int`, which specifies that the output array should contain integer values.

array([0, 1, 2, 3, 4])

In [42]:
array, step_size = np.linspace(0, 10, 5, retstep=True)
print(array)
print(step_size)

[ 0.   2.5  5.   7.5 10. ]
2.5


Random generation functions

In [4]:
arr = np.random.rand(7)
arr

array([0.91846862, 0.87604407, 0.36060506, 0.33743956, 0.12425986,
       0.66369976, 0.56642511])

In [5]:
arr = np.random.rand(3,4)
arr

array([[0.75594122, 0.84145763, 0.71423313, 0.5003644 ],
       [0.64186127, 0.08586668, 0.0352265 , 0.47413929],
       [0.69472479, 0.78002924, 0.25747084, 0.17910128]])

In [7]:
arr = np.random.randn(7)
arr

array([-0.01716482,  0.63737716, -0.39498027,  0.33199982, -3.52263998,
        0.64741564,  0.3317198 ])

In [10]:
arr = np.random.randn(2,5)
arr

array([[-2.70817488,  0.53150968,  0.81664503, -0.8988892 , -1.129558  ],
       [-0.23764368, -0.43341486,  0.86219464,  2.73644308,  0.1130859 ]])

In [13]:
arr = np.random.randint(1, 10)
arr

6

In [14]:
arr = np.random.randint(1, 10, size=7)
arr

array([6, 2, 6, 9, 9, 3, 5], dtype=int32)

In [15]:
arr = np.random.randint(1, 10, size=(3,4))
arr

array([[5, 4, 7, 8],
       [5, 9, 8, 6],
       [7, 6, 7, 4]], dtype=int32)

In [17]:
arr = np.random.randn(2,9).astype(np.float32)
arr

array([[-0.59841454, -0.5084184 ,  0.31049594,  0.24182132, -0.30817038,
        -0.47351056, -0.7268184 ,  0.5209319 , -1.8069003 ],
       [ 0.31841466,  0.2910778 ,  1.0051202 ,  0.5499599 ,  1.0402397 ,
         0.2070759 , -0.8583152 ,  1.0378628 , -1.2212785 ]],
      dtype=float32)

In [18]:
rng = np.random.default_rng()
arr = rng.integers(1, 10, size=(3,4))
arr 

array([[6, 9, 2, 5],
       [1, 3, 6, 3],
       [2, 2, 7, 9]])

In [20]:
rng = np.random.default_rng()
arr = rng.random((3,4))
arr 

array([[0.1130211 , 0.83080707, 0.42059099, 0.88718782],
       [0.63054579, 0.58539807, 0.72301063, 0.03575305],
       [0.26601949, 0.08232986, 0.8686769 , 0.61120637]])

In [21]:
rng = np.random.default_rng()
arr = rng.random(5)
arr 
#rng is an instance of the default random number generator provided by NumPy. It is used to generate random numbers in a more flexible and efficient way compared to the older `np.random` module. The `rng.random()` method generates an array of random numbers drawn from a uniform distribution over the interval [0, 1). In this case, we are generating a 1D array with 5 random numbers.

array([0.37211831, 0.28702775, 0.64667248, 0.04169073, 0.31212994])

In [27]:
arr = rng.uniform(5, 15, size=(3, 4))
arr
#uniform() function is used to create an array of random numbers drawn from a uniform distribution. It takes three arguments: low, high, and size. The low argument specifies the lower bound of the distribution, the high argument specifies the upper bound of the distribution, and the size argument specifies the shape of the output array. In this case, we are creating a 2D array with 3 rows and 4 columns, with random numbers drawn from a uniform distribution between 5 and 15.

array([[ 9.62243031, 11.92389163,  9.94752623, 11.08835913],
       [ 9.160029  , 11.64118156,  5.28668239,  9.41054345],
       [11.97594731, 12.94681492,  8.77158238,  6.10674795]])

In [28]:
arr = rng.normal(0, 1, size=(3, 4))
arr
#normal() function is used to create an array of random numbers drawn from a normal (Gaussian) distribution. It takes three arguments: loc, scale, and size. The loc argument specifies the mean of the distribution, the scale argument specifies the standard deviation of the distribution, and the size argument specifies the shape of the output array. In this case, we are creating a 2D array with 3 rows and 4 columns, with random numbers drawn from a normal distribution with a mean of 0 and a standard deviation of 1.

array([[-0.4545905 , -1.22387877,  2.07149036, -0.38813121],
       [-0.43367104,  0.33827644,  0.96894163,  2.27952475],
       [-0.09343238, -0.51919341, -0.05640793,  0.28476456]])

Array attributes

In [32]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a.shape

(3, 3)

In [34]:
a.size

9

In [35]:
a.dtype

dtype('int64')

Array methods

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a.min()
#min() function is used to find the minimum value in an array. It returns the smallest element in the array.

np.int64(1)

In [41]:
int(a.min())
#int() function is used to convert the minimum value of the array to an integer data type. This is useful when we want to ensure that the minimum value is represented as an integer, especially if the array contains floating-point numbers. In this case, since the minimum value of the array `a` is already an integer (1), the conversion does not change its value.

1

In [42]:
a.min().item()
#item() function is used to convert the minimum value of the array to a standard Python scalar type. This is useful when we want to work with the minimum value in a more general context, such as when passing it to a function that expects a scalar input. In this case, since the minimum value of the array `a` is already an integer (1), the conversion does not change its value.

1

In [43]:
a.max()

np.int64(9)

In [44]:
a.sum()

np.int64(45)

In [45]:
int(a.sum())

45

In [46]:
np.sum(a,axis=0)

array([12, 15, 18])

In [48]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [49]:
a.mean()

np.float64(5.0)

In [51]:
a.std()

np.float64(2.581988897471611)

Reshaping and resizing

In [52]:
a = np.arange(1,31)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [58]:
a = a.reshape(5,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [59]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])