In [2]:
import numpy as np

Numpy indexing and slicing of vectors

In [3]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
a[6]
#this will give the 6th index value of the array a

np.int64(17)

In [ ]:
a[1:5]
#this will give the values from index 1 to 4 of the array a

array([12, 13, 14, 15])

In [ ]:
a[1:5:1]
#this will give the values from index 1 to 4 of the array a with a step size of 1 it means it will give all the values from index 1 to 4

array([12, 13, 14, 15])

In [ ]:
a[1:7:2]
#this will give the values from index 1 to 6 of the array a with a step size of 2 it means it will give the values from index 1,3,5

array([12, 14, 16])

In [ ]:
a[1::2]

array([12, 14, 16, 18, 20])

Numpy indexing and slicing of matrix

In [13]:

a = np.arange(1,31).reshape(6,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
a[1]
#this slice out a specific row from the 2D array a.Syntax is a[row_index].

array([ 6,  7,  8,  9, 10])

In [ ]:
a[1,2]
#this will give you a specific element. Syntax is a[row_index, column_index]. 

np.int64(8)

In [ ]:
 a[0:2,1:3]
#this will give you a specific slice of the 2D array a. Syntax is a[row_start:row_end, column_start:column_end]. and in end part for both row and column the end index is exclusive. 

array([[2, 3],
       [7, 8]])

In [18]:
a[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
a[:,2]
#this will give you a specific column from the 2D array a. Syntax is a[:,column_index]. 

array([ 3,  8, 13, 18, 23, 28])

Boolean indexing

In [20]:
a = np.arange(11,21)
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [21]:
bi = a %2==0
bi

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [22]:
a = a[bi]
a

array([12, 14, 16, 18, 20])

In [23]:
bi = a>15
bi

array([False, False,  True,  True,  True])

In [24]:
a = a[bi]
a

array([16, 18, 20])