ARRAY OPERATIONS

In [21]:
import numpy as np

Arithmetic operations

In [ ]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])


In [5]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [6]:
a1-a2

array([-5, -5, -5, -5, -5])

In [7]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [8]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

In [11]:
a1**a2


array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [17]:
l = [10,20,30,40]
a = np.array(l)

In [18]:
a + 10

array([20, 30, 40, 50])

In [19]:
for i in l:
    print(i+10)

20
30
40
50


In [20]:
a3 = np.arange(1,26).reshape(5,5)
a3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [21]:
a3+10


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [22]:
a4 = np.arange(1,10).reshape(3,3)
a4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a5 = ([1,0,1])
a5

[1, 0, 1]

In [24]:
a4+a5

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

In [25]:
a4*a5

array([[1, 0, 3],
       [4, 0, 6],
       [7, 0, 9]])

In [26]:
a6 = np.array([10,20,30]).reshape(3,1)
a7 = np.array([1,2,3])
a6+a7

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [27]:
a6*a7

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

Deep and shallow copy

In [35]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
s = a[:5]
s

array([1, 2, 3, 4, 5])

In [41]:
s = s*10
s

array([10, 20, 30, 40, 50])

In [ ]:
a[4:6] *10

array([50, 60])

In [ ]:
a
b = a
#deep copy

In [45]:
b[0] =99

In [46]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [47]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operation

In [4]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [5]:
A

array([[1, 2],
       [3, 4]])

In [6]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A*B
#index wise multiplication means A[0,0]*B[0,0], A[0,1]*B[0,1] and so on. But multipilication of two matrices is different. It is not index wise multiplication. It is the dot product of two matrices. 

array([[ 5, 12],
       [21, 32]])

In [ ]:
A@B
#it is actually how we multiply two matrices. It is not index wise multiplication. It is the dot product of two matrices.


array([[19, 22],
       [43, 50]])

In [11]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [12]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.T
#this is for transpose


array([[1, 3],
       [2, 4]])

In [14]:
A+B

array([[ 6,  8],
       [10, 12]])

ADVANCE ARRAY MANIPULATION

Stacking array

In [18]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [22]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
np.vstack([a, b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.hstack([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [27]:
np.column_stack([a, b])

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [30]:
np.row_stack((a,b))

C:\Users\gauri\AppData\Local\Temp\ipykernel_29424\1307586492.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a,b))


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.stack((a, b), axis=0)
#axis=0 means it will stack the arrays vertically. same as np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
print(np.stack((a,b), axis=1))
#axis=1 means it will stack the arrays horizontally. same as np.column_stack((a,b))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
ab = np.array([[1,2],
              [3,4]])

ba = np.array([[5,6],
              [7,8]])

print(np.dstack((ab,ba)))
#it will stack the arrays depth wise. It will create a new dimension. The first array will be in the first layer and the second array will be in the second layer.

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Splitting array

In [35]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
np.hsplit(c,2)  

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [37]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
sp = np.vsplit(c,4)
#error because we cannot split the array into 3 equal parts. It can only be split into 1,2,4,8 equal parts.

In [43]:
for i in sp:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
